import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { ethers } from "ethers";
import {
  useWeb3ModalAccount,
  useWeb3ModalSigner,
} from "@web3modal/ethers5/react";

export default function Home() {
  const [hasNFT, setHasNFT] = useState(false);

  const { address, chainId, isConnected } = useWeb3ModalAccount();
  const { walletProvider } = useWeb3ModalSigner();

  const nft = process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS;

  useEffect(() => {
    const setBal = async () => {
      if (address) {
        const contract = new ethers.Contract(
          nft!,
          ["function balanceOf(address) public view returns (uint256)"],
          walletProvider
        );

        const balance = await contract.balanceOf(address);
        if (balance && BigInt(balance as any) > 0) {
          setHasNFT(true);
        } else {
          setHasNFT(false);
        }
      } else {
        setHasNFT(false);
      }
    };
    setBal();
  }, [walletProvider, nft, address]);

  const contents = <main className={styles.main}>Has access</main>;

  const header = (
    <>
      <Head>
        <title>WalletConnect | Next Starter Template</title>
        <meta name="description" content="Generated by create-wc-dapp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <w3m-button></w3m-button>

      {hasNFT ? contents : "No access"}
    </>
  );

  return header;
}
